apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: fq6b4iri7-nodejs 
  janus-idp.io/tekton: fq6b4iri7-nodejs
  backstage.io/kubernetes-id: fq6b4iri7-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fq6b4iri7-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml